name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: "Tests"
    uses: "SciML/.github/.github/workflows/tests.yml@v1"
    with:
      julia-version: "1"
      julia-arch: "x64"
    secrets: "inherit"
